#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 BoanLab @ Dankook University

"""Generate a Go syscall-number to syscall-name map for the KloudKnox monitor.

Parses __NR_* macros from a Linux unistd_64.h header and emits a Go source
file containing ``var syscall2name = map[int32]string{...}`` on stdout.

Usage:
    genSyscallMap.py [header_path] > monitor/syscalls.go

If no header path is given, the script tries common system locations.
"""

import re
import sys
from pathlib import Path

DEFAULT_PATHS = [
    "/usr/include/asm/unistd_64.h",  # glibc
    "/usr/include/x86_64-linux-gnu/asm/unistd_64.h",  # Ubuntu/Debian
]

def parse_unistd(path):
    syscalls = {}
    pat = re.compile(r"#define\s+__NR_(\w+)\s+(\d+)")
    with open(path) as f:
        for line in f:
            m = pat.match(line)
            if m:
                name, num = m.group(1), int(m.group(2))
                syscalls[num] = name
    return syscalls

def main():
    hdr = None
    for p in DEFAULT_PATHS:
        if Path(p).exists():
            hdr = p
            break
    if not hdr:
        if len(sys.argv) < 2:
            print("Usage: gen_syscall_map.py /path/to/unistd_*.h", file=sys.stderr)
            sys.exit(1)
        hdr = sys.argv[1]

    syscalls = parse_unistd(hdr)

    print("// SPDX-License-Identifier: Apache-2.0")
    print("// Copyright 2026 BoanLab @ Dankook University")
    print("")
    print("package monitor")
    print("")
    print("// Code generated by genSyscallMap.py; DO NOT EDIT.")
    print("")
    print("// syscall2name is a map of syscall numbers to their names")
    print("var syscall2name = map[int32]string{")
    for num in sorted(syscalls.keys()):
        print(f"    {num}: \"{syscalls[num]}\",")
    print("}")

if __name__ == "__main__":
    main()
