#!/usr/bin/env bash
# Judging: match alerts.jsonl records to a step's expectation.
# Relies on globals ALERTS_FILE / E2E_ROOT.

# Snapshot the current byte offset of alerts.jsonl — isolates the case from
# alerts generated by prior cases. Call before exec, pass the return into the
# matcher to scope the window.
assert_alert_offset() {
    if [[ -f "${ALERTS_FILE}" ]]; then
        stat -c%s "${ALERTS_FILE}" 2>/dev/null || echo 0
    else
        echo 0
    fi
}

# Args: offset policy_name pod_label [window=3]
# Emit newline-delimited JSON of matching alerts on stdout.
#
# For ingress policies the alert is generated in the destination pod's context,
# not the source pod executing the step.  Derive the policy's target container
# name from the policy name prefix (e.g. ubuntu-2-net-peer-ingress-block →
# ubuntu-2-container) so ingress alerts are still matched correctly.
assert_collect_alerts() {
    local offset="$1" policy="$2" pod_label="$3" window="${4:-3}"
    # policy name prefix: first two dash-separated tokens (ubuntu-2, group-1, …)
    local target_container
    target_container="$(printf '%s' "${policy}" | cut -d'-' -f1,2)-container"
    local deadline=$((SECONDS + window))
    local result=""
    while (( SECONDS < deadline )); do
        if [[ -f "${ALERTS_FILE}" ]]; then
            result="$(tail -c "+$((offset + 1))" "${ALERTS_FILE}" 2>/dev/null \
                | jq -c --arg p "${policy}" --arg pod "${pod_label}" --arg tc "${target_container}" \
                    'select(.policyName == $p and (.containerName == null or .containerName == $pod or .containerName == ($pod + "-container") or .containerName == $tc or $pod == ""))' \
                2>/dev/null || true)"
            if [[ -n "${result}" ]]; then
                printf '%s\n' "${result}"
                return 0
            fi
        fi
        sleep 0.25
    done
    if [[ -f "${ALERTS_FILE}" ]]; then
        tail -c "+$((offset + 1))" "${ALERTS_FILE}" 2>/dev/null \
            | jq -c --arg p "${policy}" --arg pod "${pod_label}" --arg tc "${target_container}" \
                'select(.policyName == $p and (.containerName == $pod or .containerName == ($pod + "-container") or .containerName == $tc or $pod == ""))' \
            2>/dev/null || true
    fi
}

# Judge a step result. Returns 0 for PASS, 1 for FAIL.
# Exports ASSERT_VERDICT (PASS|FAIL) and ASSERT_REASON (human-readable).
# Args: exit_code expect policy pod_label offset [window]
assert_step() {
    local exit_code="$1" expect="$2" policy="$3" pod_label="$4" offset="$5"
    local window="${6:-3}"
    local alerts total block_count audit_count

    if [[ "${expect}" == "allowed" && "${exit_code}" -ne 0 ]]; then
        ASSERT_VERDICT=FAIL
        ASSERT_REASON="expected allowed but exit=${exit_code}"
        return 1
    fi

    alerts="$(assert_collect_alerts "${offset}" "${policy}" "${pod_label}" "${window}")"
    if [[ -z "${alerts}" ]]; then
        total=0; block_count=0; audit_count=0
    else
        total=$(printf '%s\n' "${alerts}" | grep -c .)
        # Count as "block" either an explicit Block policy, or an Allow/whitelist
        # policy whose enforcement actually denied the operation (retCode=Blocked).
        block_count=$(printf '%s\n' "${alerts}" \
            | grep -cE '"policyAction":"Block"|"retCode":"Blocked"' || true)
        audit_count=$(printf '%s\n' "${alerts}" | grep -c '"policyAction":"Audit"' || true)
    fi

    local counts="exit=${exit_code} alerts(total=${total} block=${block_count} audit=${audit_count})"
    case "${expect}" in
        allowed)
            if [[ "${exit_code}" -eq 0 && "${total}" -eq 0 ]]; then
                ASSERT_VERDICT=PASS
                ASSERT_REASON="${counts}"
                return 0
            fi
            ASSERT_VERDICT=FAIL
            ASSERT_REASON="expected allowed but ${counts}"
            return 1
            ;;
        blocked)
            if [[ "${block_count}" -gt 0 ]]; then
                ASSERT_VERDICT=PASS
                ASSERT_REASON="${counts}"
                return 0
            fi
            ASSERT_VERDICT=FAIL
            ASSERT_REASON="expected blocked but ${counts}"
            return 1
            ;;
        audited)
            if [[ "${audit_count}" -gt 0 && "${exit_code}" -eq 0 ]]; then
                ASSERT_VERDICT=PASS
                ASSERT_REASON="${counts}"
                return 0
            fi
            ASSERT_VERDICT=FAIL
            ASSERT_REASON="expected audited but ${counts}"
            return 1
            ;;
        *)
            ASSERT_VERDICT=FAIL
            ASSERT_REASON="unknown expect '${expect}'"
            return 1
            ;;
    esac
}
