// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 BoanLab @ Dankook University

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: kloudknox.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KloudKnox_EventStream_FullMethodName = "/protobuf.KloudKnox/EventStream"
	KloudKnox_AlertStream_FullMethodName = "/protobuf.KloudKnox/AlertStream"
	KloudKnox_LogStream_FullMethodName   = "/protobuf.KloudKnox/LogStream"
)

// KloudKnoxClient is the client API for KloudKnox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KloudKnox exposes three server-streaming RPCs for real-time data export.
type KloudKnoxClient interface {
	// EventStream streams raw system events matching the supplied filter.
	EventStream(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// AlertStream streams policy-enforcement alerts matching the supplied filter.
	AlertStream(ctx context.Context, in *AlertFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Alert], error)
	// LogStream streams daemon log entries matching the supplied filter.
	LogStream(ctx context.Context, in *LogFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error)
}

type kloudKnoxClient struct {
	cc grpc.ClientConnInterface
}

func NewKloudKnoxClient(cc grpc.ClientConnInterface) KloudKnoxClient {
	return &kloudKnoxClient{cc}
}

func (c *kloudKnoxClient) EventStream(ctx context.Context, in *EventFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KloudKnox_ServiceDesc.Streams[0], KloudKnox_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventFilter, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KloudKnox_EventStreamClient = grpc.ServerStreamingClient[Event]

func (c *kloudKnoxClient) AlertStream(ctx context.Context, in *AlertFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Alert], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KloudKnox_ServiceDesc.Streams[1], KloudKnox_AlertStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AlertFilter, Alert]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KloudKnox_AlertStreamClient = grpc.ServerStreamingClient[Alert]

func (c *kloudKnoxClient) LogStream(ctx context.Context, in *LogFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KloudKnox_ServiceDesc.Streams[2], KloudKnox_LogStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogFilter, Log]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KloudKnox_LogStreamClient = grpc.ServerStreamingClient[Log]

// KloudKnoxServer is the server API for KloudKnox service.
// All implementations must embed UnimplementedKloudKnoxServer
// for forward compatibility.
//
// KloudKnox exposes three server-streaming RPCs for real-time data export.
type KloudKnoxServer interface {
	// EventStream streams raw system events matching the supplied filter.
	EventStream(*EventFilter, grpc.ServerStreamingServer[Event]) error
	// AlertStream streams policy-enforcement alerts matching the supplied filter.
	AlertStream(*AlertFilter, grpc.ServerStreamingServer[Alert]) error
	// LogStream streams daemon log entries matching the supplied filter.
	LogStream(*LogFilter, grpc.ServerStreamingServer[Log]) error
	mustEmbedUnimplementedKloudKnoxServer()
}

// UnimplementedKloudKnoxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKloudKnoxServer struct{}

func (UnimplementedKloudKnoxServer) EventStream(*EventFilter, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedKloudKnoxServer) AlertStream(*AlertFilter, grpc.ServerStreamingServer[Alert]) error {
	return status.Error(codes.Unimplemented, "method AlertStream not implemented")
}
func (UnimplementedKloudKnoxServer) LogStream(*LogFilter, grpc.ServerStreamingServer[Log]) error {
	return status.Error(codes.Unimplemented, "method LogStream not implemented")
}
func (UnimplementedKloudKnoxServer) mustEmbedUnimplementedKloudKnoxServer() {}
func (UnimplementedKloudKnoxServer) testEmbeddedByValue()                   {}

// UnsafeKloudKnoxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KloudKnoxServer will
// result in compilation errors.
type UnsafeKloudKnoxServer interface {
	mustEmbedUnimplementedKloudKnoxServer()
}

func RegisterKloudKnoxServer(s grpc.ServiceRegistrar, srv KloudKnoxServer) {
	// If the following call panics, it indicates UnimplementedKloudKnoxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KloudKnox_ServiceDesc, srv)
}

func _KloudKnox_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KloudKnoxServer).EventStream(m, &grpc.GenericServerStream[EventFilter, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KloudKnox_EventStreamServer = grpc.ServerStreamingServer[Event]

func _KloudKnox_AlertStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AlertFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KloudKnoxServer).AlertStream(m, &grpc.GenericServerStream[AlertFilter, Alert]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KloudKnox_AlertStreamServer = grpc.ServerStreamingServer[Alert]

func _KloudKnox_LogStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KloudKnoxServer).LogStream(m, &grpc.GenericServerStream[LogFilter, Log]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KloudKnox_LogStreamServer = grpc.ServerStreamingServer[Log]

// KloudKnox_ServiceDesc is the grpc.ServiceDesc for KloudKnox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KloudKnox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.KloudKnox",
	HandlerType: (*KloudKnoxServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _KloudKnox_EventStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AlertStream",
			Handler:       _KloudKnox_AlertStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LogStream",
			Handler:       _KloudKnox_LogStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kloudknox.proto",
}
