// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 BoanLab @ Dankook University

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: kloudknox.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a raw system event captured by the eBPF monitor.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	Timestamp uint64 `protobuf:"varint,11,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"` // nanoseconds since epoch
	CPUID     uint32 `protobuf:"varint,12,opt,name=CPUID,proto3" json:"CPUID,omitempty"`         // CPU on which the event occurred
	SeqNum    uint32 `protobuf:"varint,13,opt,name=SeqNum,proto3" json:"SeqNum,omitempty"`       // monotonic per-CPU sequence number
	// Host-level process identifiers (outside the container namespace)
	HostPPID int32 `protobuf:"varint,21,opt,name=HostPPID,proto3" json:"HostPPID,omitempty"`
	HostPID  int32 `protobuf:"varint,22,opt,name=HostPID,proto3" json:"HostPID,omitempty"`
	HostTID  int32 `protobuf:"varint,23,opt,name=HostTID,proto3" json:"HostTID,omitempty"`
	// Container-namespace process identifiers
	PPID int32 `protobuf:"varint,31,opt,name=PPID,proto3" json:"PPID,omitempty"`
	PID  int32 `protobuf:"varint,32,opt,name=PID,proto3" json:"PID,omitempty"`
	TID  int32 `protobuf:"varint,33,opt,name=TID,proto3" json:"TID,omitempty"`
	// Credentials
	UID uint32 `protobuf:"varint,41,opt,name=UID,proto3" json:"UID,omitempty"`
	GID uint32 `protobuf:"varint,42,opt,name=GID,proto3" json:"GID,omitempty"`
	// Syscall information
	EventID   int32  `protobuf:"varint,51,opt,name=EventID,proto3" json:"EventID,omitempty"`    // numeric syscall identifier
	EventName string `protobuf:"bytes,52,opt,name=EventName,proto3" json:"EventName,omitempty"` // syscall name (e.g., "open", "connect")
	RetVal    int32  `protobuf:"varint,53,opt,name=RetVal,proto3" json:"RetVal,omitempty"`      // raw return value
	RetCode   string `protobuf:"bytes,54,opt,name=RetCode,proto3" json:"RetCode,omitempty"`     // human-readable return code (e.g., "SUCCESS", "EPERM")
	// Semantic classification
	Source    string `protobuf:"bytes,61,opt,name=Source,proto3" json:"Source,omitempty"`       // origin subsystem (e.g., "container")
	Category  string `protobuf:"bytes,62,opt,name=Category,proto3" json:"Category,omitempty"`   // activity category (e.g., "File", "Network", "Process")
	Operation string `protobuf:"bytes,63,opt,name=Operation,proto3" json:"Operation,omitempty"` // specific operation (e.g., "Read", "Write", "Connect")
	Resource  string `protobuf:"bytes,64,opt,name=Resource,proto3" json:"Resource,omitempty"`   // target resource (file path, address, etc.)
	Data      string `protobuf:"bytes,65,opt,name=Data,proto3" json:"Data,omitempty"`           // additional context in key=value format
	// Kubernetes / container identity
	NodeName      string `protobuf:"bytes,71,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	NamespaceName string `protobuf:"bytes,72,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	PodName       string `protobuf:"bytes,73,opt,name=PodName,proto3" json:"PodName,omitempty"`
	ContainerName string `protobuf:"bytes,74,opt,name=ContainerName,proto3" json:"ContainerName,omitempty"`
	Labels        string `protobuf:"bytes,75,opt,name=Labels,proto3" json:"Labels,omitempty"` // pod labels serialized as "key=value,..." pairs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kloudknox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kloudknox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kloudknox_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetCPUID() uint32 {
	if x != nil {
		return x.CPUID
	}
	return 0
}

func (x *Event) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Event) GetHostPPID() int32 {
	if x != nil {
		return x.HostPPID
	}
	return 0
}

func (x *Event) GetHostPID() int32 {
	if x != nil {
		return x.HostPID
	}
	return 0
}

func (x *Event) GetHostTID() int32 {
	if x != nil {
		return x.HostTID
	}
	return 0
}

func (x *Event) GetPPID() int32 {
	if x != nil {
		return x.PPID
	}
	return 0
}

func (x *Event) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Event) GetTID() int32 {
	if x != nil {
		return x.TID
	}
	return 0
}

func (x *Event) GetUID() uint32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Event) GetGID() uint32 {
	if x != nil {
		return x.GID
	}
	return 0
}

func (x *Event) GetEventID() int32 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *Event) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Event) GetRetVal() int32 {
	if x != nil {
		return x.RetVal
	}
	return 0
}

func (x *Event) GetRetCode() string {
	if x != nil {
		return x.RetCode
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Event) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Event) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Event) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Event) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *Event) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Event) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Event) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

// EventFilter selects which events are delivered on an EventStream.
// Empty fields match all records. PodName and ContainerName are matched
// by prefix; all other fields require an exact match.
type EventFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,11,opt,name=EventName,proto3" json:"EventName,omitempty"`
	Source        string                 `protobuf:"bytes,21,opt,name=Source,proto3" json:"Source,omitempty"`
	Category      string                 `protobuf:"bytes,22,opt,name=Category,proto3" json:"Category,omitempty"`
	Operation     string                 `protobuf:"bytes,23,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Resource      string                 `protobuf:"bytes,24,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Data          string                 `protobuf:"bytes,25,opt,name=Data,proto3" json:"Data,omitempty"`
	NodeName      string                 `protobuf:"bytes,31,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	NamespaceName string                 `protobuf:"bytes,32,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	PodName       string                 `protobuf:"bytes,33,opt,name=PodName,proto3" json:"PodName,omitempty"`
	ContainerName string                 `protobuf:"bytes,34,opt,name=ContainerName,proto3" json:"ContainerName,omitempty"`
	Labels        string                 `protobuf:"bytes,35,opt,name=Labels,proto3" json:"Labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_kloudknox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_kloudknox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_kloudknox_proto_rawDescGZIP(), []int{1}
}

func (x *EventFilter) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *EventFilter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EventFilter) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *EventFilter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *EventFilter) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *EventFilter) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EventFilter) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *EventFilter) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *EventFilter) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *EventFilter) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *EventFilter) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

// Alert is an Event that matched an active enforcement policy.
// All Event fields are present; the two additional fields carry
// policy enforcement context.
type Alert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	Timestamp uint64 `protobuf:"varint,11,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	CPUID     uint32 `protobuf:"varint,12,opt,name=CPUID,proto3" json:"CPUID,omitempty"`
	SeqNum    uint32 `protobuf:"varint,13,opt,name=SeqNum,proto3" json:"SeqNum,omitempty"`
	// Host-level process identifiers
	HostPPID int32 `protobuf:"varint,21,opt,name=HostPPID,proto3" json:"HostPPID,omitempty"`
	HostPID  int32 `protobuf:"varint,22,opt,name=HostPID,proto3" json:"HostPID,omitempty"`
	HostTID  int32 `protobuf:"varint,23,opt,name=HostTID,proto3" json:"HostTID,omitempty"`
	// Container-namespace process identifiers
	PPID int32 `protobuf:"varint,31,opt,name=PPID,proto3" json:"PPID,omitempty"`
	PID  int32 `protobuf:"varint,32,opt,name=PID,proto3" json:"PID,omitempty"`
	TID  int32 `protobuf:"varint,33,opt,name=TID,proto3" json:"TID,omitempty"`
	// Credentials
	UID uint32 `protobuf:"varint,41,opt,name=UID,proto3" json:"UID,omitempty"`
	GID uint32 `protobuf:"varint,42,opt,name=GID,proto3" json:"GID,omitempty"`
	// Syscall information
	EventID   int32  `protobuf:"varint,51,opt,name=EventID,proto3" json:"EventID,omitempty"`
	EventName string `protobuf:"bytes,52,opt,name=EventName,proto3" json:"EventName,omitempty"`
	RetVal    int32  `protobuf:"varint,53,opt,name=RetVal,proto3" json:"RetVal,omitempty"`
	RetCode   string `protobuf:"bytes,54,opt,name=RetCode,proto3" json:"RetCode,omitempty"`
	// Semantic classification
	Source    string `protobuf:"bytes,61,opt,name=Source,proto3" json:"Source,omitempty"`
	Category  string `protobuf:"bytes,62,opt,name=Category,proto3" json:"Category,omitempty"`
	Operation string `protobuf:"bytes,63,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Resource  string `protobuf:"bytes,64,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Data      string `protobuf:"bytes,65,opt,name=Data,proto3" json:"Data,omitempty"`
	// Kubernetes / container identity
	NodeName      string `protobuf:"bytes,71,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	NamespaceName string `protobuf:"bytes,72,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	PodName       string `protobuf:"bytes,73,opt,name=PodName,proto3" json:"PodName,omitempty"`
	ContainerName string `protobuf:"bytes,74,opt,name=ContainerName,proto3" json:"ContainerName,omitempty"`
	Labels        string `protobuf:"bytes,75,opt,name=Labels,proto3" json:"Labels,omitempty"`
	// Policy enforcement context
	PolicyName    string `protobuf:"bytes,81,opt,name=PolicyName,proto3" json:"PolicyName,omitempty"`     // name of the policy that triggered the alert
	PolicyAction  string `protobuf:"bytes,82,opt,name=PolicyAction,proto3" json:"PolicyAction,omitempty"` // action taken: "Audit" or "Block"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_kloudknox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_kloudknox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_kloudknox_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Alert) GetCPUID() uint32 {
	if x != nil {
		return x.CPUID
	}
	return 0
}

func (x *Alert) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Alert) GetHostPPID() int32 {
	if x != nil {
		return x.HostPPID
	}
	return 0
}

func (x *Alert) GetHostPID() int32 {
	if x != nil {
		return x.HostPID
	}
	return 0
}

func (x *Alert) GetHostTID() int32 {
	if x != nil {
		return x.HostTID
	}
	return 0
}

func (x *Alert) GetPPID() int32 {
	if x != nil {
		return x.PPID
	}
	return 0
}

func (x *Alert) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Alert) GetTID() int32 {
	if x != nil {
		return x.TID
	}
	return 0
}

func (x *Alert) GetUID() uint32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Alert) GetGID() uint32 {
	if x != nil {
		return x.GID
	}
	return 0
}

func (x *Alert) GetEventID() int32 {
	if x != nil {
		return x.EventID
	}
	return 0
}

func (x *Alert) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *Alert) GetRetVal() int32 {
	if x != nil {
		return x.RetVal
	}
	return 0
}

func (x *Alert) GetRetCode() string {
	if x != nil {
		return x.RetCode
	}
	return ""
}

func (x *Alert) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Alert) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Alert) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Alert) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Alert) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Alert) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Alert) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *Alert) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Alert) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Alert) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *Alert) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Alert) GetPolicyAction() string {
	if x != nil {
		return x.PolicyAction
	}
	return ""
}

// AlertFilter selects which alerts are delivered on an AlertStream.
// Matching rules are identical to EventFilter.
type AlertFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,11,opt,name=EventName,proto3" json:"EventName,omitempty"`
	Source        string                 `protobuf:"bytes,21,opt,name=Source,proto3" json:"Source,omitempty"`
	Category      string                 `protobuf:"bytes,22,opt,name=Category,proto3" json:"Category,omitempty"`
	Operation     string                 `protobuf:"bytes,23,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Resource      string                 `protobuf:"bytes,24,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Data          string                 `protobuf:"bytes,25,opt,name=Data,proto3" json:"Data,omitempty"`
	NodeName      string                 `protobuf:"bytes,31,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	NamespaceName string                 `protobuf:"bytes,32,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	PodName       string                 `protobuf:"bytes,33,opt,name=PodName,proto3" json:"PodName,omitempty"`
	ContainerName string                 `protobuf:"bytes,34,opt,name=ContainerName,proto3" json:"ContainerName,omitempty"`
	Labels        string                 `protobuf:"bytes,35,opt,name=Labels,proto3" json:"Labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertFilter) Reset() {
	*x = AlertFilter{}
	mi := &file_kloudknox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertFilter) ProtoMessage() {}

func (x *AlertFilter) ProtoReflect() protoreflect.Message {
	mi := &file_kloudknox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertFilter.ProtoReflect.Descriptor instead.
func (*AlertFilter) Descriptor() ([]byte, []int) {
	return file_kloudknox_proto_rawDescGZIP(), []int{3}
}

func (x *AlertFilter) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *AlertFilter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AlertFilter) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AlertFilter) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AlertFilter) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AlertFilter) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *AlertFilter) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AlertFilter) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *AlertFilter) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AlertFilter) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *AlertFilter) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

// Log carries a single structured log entry emitted by the KloudKnox daemon.
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,11,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"` // nanoseconds since epoch
	Level         string                 `protobuf:"bytes,21,opt,name=Level,proto3" json:"Level,omitempty"`          // severity: "debug", "info", "warn", "error"
	Message       string                 `protobuf:"bytes,22,opt,name=Message,proto3" json:"Message,omitempty"`      // log message text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_kloudknox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_kloudknox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_kloudknox_proto_rawDescGZIP(), []int{4}
}

func (x *Log) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// LogFilter selects which log entries are delivered on a LogStream.
// Set Level to a specific severity to receive only entries at that level.
// Leave Level empty to receive all entries.
type LogFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,11,opt,name=Level,proto3" json:"Level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFilter) Reset() {
	*x = LogFilter{}
	mi := &file_kloudknox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFilter) ProtoMessage() {}

func (x *LogFilter) ProtoReflect() protoreflect.Message {
	mi := &file_kloudknox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFilter.ProtoReflect.Descriptor instead.
func (*LogFilter) Descriptor() ([]byte, []int) {
	return file_kloudknox_proto_rawDescGZIP(), []int{5}
}

func (x *LogFilter) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_kloudknox_proto protoreflect.FileDescriptor

const file_kloudknox_proto_rawDesc = "" +
	"\n" +
	"\x0fkloudknox.proto\x12\bprotobuf\"\x85\x05\n" +
	"\x05Event\x12\x1c\n" +
	"\tTimestamp\x18\v \x01(\x04R\tTimestamp\x12\x14\n" +
	"\x05CPUID\x18\f \x01(\rR\x05CPUID\x12\x16\n" +
	"\x06SeqNum\x18\r \x01(\rR\x06SeqNum\x12\x1a\n" +
	"\bHostPPID\x18\x15 \x01(\x05R\bHostPPID\x12\x18\n" +
	"\aHostPID\x18\x16 \x01(\x05R\aHostPID\x12\x18\n" +
	"\aHostTID\x18\x17 \x01(\x05R\aHostTID\x12\x12\n" +
	"\x04PPID\x18\x1f \x01(\x05R\x04PPID\x12\x10\n" +
	"\x03PID\x18  \x01(\x05R\x03PID\x12\x10\n" +
	"\x03TID\x18! \x01(\x05R\x03TID\x12\x10\n" +
	"\x03UID\x18) \x01(\rR\x03UID\x12\x10\n" +
	"\x03GID\x18* \x01(\rR\x03GID\x12\x18\n" +
	"\aEventID\x183 \x01(\x05R\aEventID\x12\x1c\n" +
	"\tEventName\x184 \x01(\tR\tEventName\x12\x16\n" +
	"\x06RetVal\x185 \x01(\x05R\x06RetVal\x12\x18\n" +
	"\aRetCode\x186 \x01(\tR\aRetCode\x12\x16\n" +
	"\x06Source\x18= \x01(\tR\x06Source\x12\x1a\n" +
	"\bCategory\x18> \x01(\tR\bCategory\x12\x1c\n" +
	"\tOperation\x18? \x01(\tR\tOperation\x12\x1a\n" +
	"\bResource\x18@ \x01(\tR\bResource\x12\x12\n" +
	"\x04Data\x18A \x01(\tR\x04Data\x12\x1a\n" +
	"\bNodeName\x18G \x01(\tR\bNodeName\x12$\n" +
	"\rNamespaceName\x18H \x01(\tR\rNamespaceName\x12\x18\n" +
	"\aPodName\x18I \x01(\tR\aPodName\x12$\n" +
	"\rContainerName\x18J \x01(\tR\rContainerName\x12\x16\n" +
	"\x06Labels\x18K \x01(\tR\x06Labels\"\xc7\x02\n" +
	"\vEventFilter\x12\x1c\n" +
	"\tEventName\x18\v \x01(\tR\tEventName\x12\x16\n" +
	"\x06Source\x18\x15 \x01(\tR\x06Source\x12\x1a\n" +
	"\bCategory\x18\x16 \x01(\tR\bCategory\x12\x1c\n" +
	"\tOperation\x18\x17 \x01(\tR\tOperation\x12\x1a\n" +
	"\bResource\x18\x18 \x01(\tR\bResource\x12\x12\n" +
	"\x04Data\x18\x19 \x01(\tR\x04Data\x12\x1a\n" +
	"\bNodeName\x18\x1f \x01(\tR\bNodeName\x12$\n" +
	"\rNamespaceName\x18  \x01(\tR\rNamespaceName\x12\x18\n" +
	"\aPodName\x18! \x01(\tR\aPodName\x12$\n" +
	"\rContainerName\x18\" \x01(\tR\rContainerName\x12\x16\n" +
	"\x06Labels\x18# \x01(\tR\x06Labels\"\xc9\x05\n" +
	"\x05Alert\x12\x1c\n" +
	"\tTimestamp\x18\v \x01(\x04R\tTimestamp\x12\x14\n" +
	"\x05CPUID\x18\f \x01(\rR\x05CPUID\x12\x16\n" +
	"\x06SeqNum\x18\r \x01(\rR\x06SeqNum\x12\x1a\n" +
	"\bHostPPID\x18\x15 \x01(\x05R\bHostPPID\x12\x18\n" +
	"\aHostPID\x18\x16 \x01(\x05R\aHostPID\x12\x18\n" +
	"\aHostTID\x18\x17 \x01(\x05R\aHostTID\x12\x12\n" +
	"\x04PPID\x18\x1f \x01(\x05R\x04PPID\x12\x10\n" +
	"\x03PID\x18  \x01(\x05R\x03PID\x12\x10\n" +
	"\x03TID\x18! \x01(\x05R\x03TID\x12\x10\n" +
	"\x03UID\x18) \x01(\rR\x03UID\x12\x10\n" +
	"\x03GID\x18* \x01(\rR\x03GID\x12\x18\n" +
	"\aEventID\x183 \x01(\x05R\aEventID\x12\x1c\n" +
	"\tEventName\x184 \x01(\tR\tEventName\x12\x16\n" +
	"\x06RetVal\x185 \x01(\x05R\x06RetVal\x12\x18\n" +
	"\aRetCode\x186 \x01(\tR\aRetCode\x12\x16\n" +
	"\x06Source\x18= \x01(\tR\x06Source\x12\x1a\n" +
	"\bCategory\x18> \x01(\tR\bCategory\x12\x1c\n" +
	"\tOperation\x18? \x01(\tR\tOperation\x12\x1a\n" +
	"\bResource\x18@ \x01(\tR\bResource\x12\x12\n" +
	"\x04Data\x18A \x01(\tR\x04Data\x12\x1a\n" +
	"\bNodeName\x18G \x01(\tR\bNodeName\x12$\n" +
	"\rNamespaceName\x18H \x01(\tR\rNamespaceName\x12\x18\n" +
	"\aPodName\x18I \x01(\tR\aPodName\x12$\n" +
	"\rContainerName\x18J \x01(\tR\rContainerName\x12\x16\n" +
	"\x06Labels\x18K \x01(\tR\x06Labels\x12\x1e\n" +
	"\n" +
	"PolicyName\x18Q \x01(\tR\n" +
	"PolicyName\x12\"\n" +
	"\fPolicyAction\x18R \x01(\tR\fPolicyAction\"\xc7\x02\n" +
	"\vAlertFilter\x12\x1c\n" +
	"\tEventName\x18\v \x01(\tR\tEventName\x12\x16\n" +
	"\x06Source\x18\x15 \x01(\tR\x06Source\x12\x1a\n" +
	"\bCategory\x18\x16 \x01(\tR\bCategory\x12\x1c\n" +
	"\tOperation\x18\x17 \x01(\tR\tOperation\x12\x1a\n" +
	"\bResource\x18\x18 \x01(\tR\bResource\x12\x12\n" +
	"\x04Data\x18\x19 \x01(\tR\x04Data\x12\x1a\n" +
	"\bNodeName\x18\x1f \x01(\tR\bNodeName\x12$\n" +
	"\rNamespaceName\x18  \x01(\tR\rNamespaceName\x12\x18\n" +
	"\aPodName\x18! \x01(\tR\aPodName\x12$\n" +
	"\rContainerName\x18\" \x01(\tR\rContainerName\x12\x16\n" +
	"\x06Labels\x18# \x01(\tR\x06Labels\"S\n" +
	"\x03Log\x12\x1c\n" +
	"\tTimestamp\x18\v \x01(\x04R\tTimestamp\x12\x14\n" +
	"\x05Level\x18\x15 \x01(\tR\x05Level\x12\x18\n" +
	"\aMessage\x18\x16 \x01(\tR\aMessage\"!\n" +
	"\tLogFilter\x12\x14\n" +
	"\x05Level\x18\v \x01(\tR\x05Level2\xb0\x01\n" +
	"\tKloudKnox\x127\n" +
	"\vEventStream\x12\x15.protobuf.EventFilter\x1a\x0f.protobuf.Event0\x01\x127\n" +
	"\vAlertStream\x12\x15.protobuf.AlertFilter\x1a\x0f.protobuf.Alert0\x01\x121\n" +
	"\tLogStream\x12\x13.protobuf.LogFilter\x1a\r.protobuf.Log0\x01B'Z%github.com/boanlab/KloudKnox/protobufb\x06proto3"

var (
	file_kloudknox_proto_rawDescOnce sync.Once
	file_kloudknox_proto_rawDescData []byte
)

func file_kloudknox_proto_rawDescGZIP() []byte {
	file_kloudknox_proto_rawDescOnce.Do(func() {
		file_kloudknox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kloudknox_proto_rawDesc), len(file_kloudknox_proto_rawDesc)))
	})
	return file_kloudknox_proto_rawDescData
}

var file_kloudknox_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kloudknox_proto_goTypes = []any{
	(*Event)(nil),       // 0: protobuf.Event
	(*EventFilter)(nil), // 1: protobuf.EventFilter
	(*Alert)(nil),       // 2: protobuf.Alert
	(*AlertFilter)(nil), // 3: protobuf.AlertFilter
	(*Log)(nil),         // 4: protobuf.Log
	(*LogFilter)(nil),   // 5: protobuf.LogFilter
}
var file_kloudknox_proto_depIdxs = []int32{
	1, // 0: protobuf.KloudKnox.EventStream:input_type -> protobuf.EventFilter
	3, // 1: protobuf.KloudKnox.AlertStream:input_type -> protobuf.AlertFilter
	5, // 2: protobuf.KloudKnox.LogStream:input_type -> protobuf.LogFilter
	0, // 3: protobuf.KloudKnox.EventStream:output_type -> protobuf.Event
	2, // 4: protobuf.KloudKnox.AlertStream:output_type -> protobuf.Alert
	4, // 5: protobuf.KloudKnox.LogStream:output_type -> protobuf.Log
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kloudknox_proto_init() }
func file_kloudknox_proto_init() {
	if File_kloudknox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kloudknox_proto_rawDesc), len(file_kloudknox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kloudknox_proto_goTypes,
		DependencyIndexes: file_kloudknox_proto_depIdxs,
		MessageInfos:      file_kloudknox_proto_msgTypes,
	}.Build()
	File_kloudknox_proto = out.File
	file_kloudknox_proto_goTypes = nil
	file_kloudknox_proto_depIdxs = nil
}
