//go:build !ignore_autogenerated

// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 BoanLab @ Dankook University

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapabilityRule) DeepCopyInto(out *CapabilityRule) {
	*out = *in
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapabilityRule.
func (in *CapabilityRule) DeepCopy() *CapabilityRule {
	if in == nil {
		return nil
	}
	out := new(CapabilityRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileRule) DeepCopyInto(out *FileRule) {
	*out = *in
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileRule.
func (in *FileRule) DeepCopy() *FileRule {
	if in == nil {
		return nil
	}
	out := new(FileRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPBlock) DeepCopyInto(out *IPBlock) {
	*out = *in
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPBlock.
func (in *IPBlock) DeepCopy() *IPBlock {
	if in == nil {
		return nil
	}
	out := new(IPBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KloudKnoxPolicy) DeepCopyInto(out *KloudKnoxPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KloudKnoxPolicy.
func (in *KloudKnoxPolicy) DeepCopy() *KloudKnoxPolicy {
	if in == nil {
		return nil
	}
	out := new(KloudKnoxPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KloudKnoxPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KloudKnoxPolicyList) DeepCopyInto(out *KloudKnoxPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KloudKnoxPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KloudKnoxPolicyList.
func (in *KloudKnoxPolicyList) DeepCopy() *KloudKnoxPolicyList {
	if in == nil {
		return nil
	}
	out := new(KloudKnoxPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KloudKnoxPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KloudKnoxPolicySpec) DeepCopyInto(out *KloudKnoxPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Process != nil {
		in, out := &in.Process, &out.Process
		*out = make([]ProcessRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = make([]FileRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = make([]NetworkRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Capability != nil {
		in, out := &in.Capability, &out.Capability
		*out = make([]CapabilityRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IPC != nil {
		in, out := &in.IPC, &out.IPC
		*out = new(IPCRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KloudKnoxPolicySpec.
func (in *KloudKnoxPolicySpec) DeepCopy() *KloudKnoxPolicySpec {
	if in == nil {
		return nil
	}
	out := new(KloudKnoxPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KloudKnoxPolicyStatus) DeepCopyInto(out *KloudKnoxPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KloudKnoxPolicyStatus.
func (in *KloudKnoxPolicyStatus) DeepCopy() *KloudKnoxPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(KloudKnoxPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkRule) DeepCopyInto(out *NetworkRule) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.IPBlock.DeepCopyInto(&out.IPBlock)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]Port, len(*in))
		copy(*out, *in)
	}
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkRule.
func (in *NetworkRule) DeepCopy() *NetworkRule {
	if in == nil {
		return nil
	}
	out := new(NetworkRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Port) DeepCopyInto(out *Port) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Port.
func (in *Port) DeepCopy() *Port {
	if in == nil {
		return nil
	}
	out := new(Port)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessRule) DeepCopyInto(out *ProcessRule) {
	*out = *in
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessRule.
func (in *ProcessRule) DeepCopy() *ProcessRule {
	if in == nil {
		return nil
	}
	out := new(ProcessRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceMatch) DeepCopyInto(out *SourceMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceMatch.
func (in *SourceMatch) DeepCopy() *SourceMatch {
	if in == nil {
		return nil
	}
	out := new(SourceMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPCRules) DeepCopyInto(out *IPCRules) {
	*out = *in
	if in.Unix != nil {
		in, out := &in.Unix, &out.Unix
		*out = make([]UnixRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Signal != nil {
		in, out := &in.Signal, &out.Signal
		*out = make([]SignalRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ptrace != nil {
		in, out := &in.Ptrace, &out.Ptrace
		*out = make([]PtraceRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPCRules.
func (in *IPCRules) DeepCopy() *IPCRules {
	if in == nil {
		return nil
	}
	out := new(IPCRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnixRule) DeepCopyInto(out *UnixRule) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnixRule.
func (in *UnixRule) DeepCopy() *UnixRule {
	if in == nil {
		return nil
	}
	out := new(UnixRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalRule) DeepCopyInto(out *SignalRule) {
	*out = *in
	if in.Signals != nil {
		in, out := &in.Signals, &out.Signals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalRule.
func (in *SignalRule) DeepCopy() *SignalRule {
	if in == nil {
		return nil
	}
	out := new(SignalRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PtraceRule) DeepCopyInto(out *PtraceRule) {
	*out = *in
	if in.FromSource != nil {
		in, out := &in.FromSource, &out.FromSource
		*out = make([]SourceMatch, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PtraceRule.
func (in *PtraceRule) DeepCopy() *PtraceRule {
	if in == nil {
		return nil
	}
	out := new(PtraceRule)
	in.DeepCopyInto(out)
	return out
}
