// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package monitor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadSystem_events returns the embedded CollectionSpec for system_events.
func loadSystem_events() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_System_eventsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load system_events: %w", err)
	}

	return spec, err
}

// loadSystem_eventsObjects loads system_events and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*system_eventsObjects
//	*system_eventsPrograms
//	*system_eventsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSystem_eventsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSystem_events()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// system_eventsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type system_eventsSpecs struct {
	system_eventsProgramSpecs
	system_eventsMapSpecs
	system_eventsVariableSpecs
}

// system_eventsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type system_eventsProgramSpecs struct {
	KprobeCapCapable                    *ebpf.ProgramSpec `ebpf:"kprobe__cap_capable"`
	KprobeFilpClose                     *ebpf.ProgramSpec `ebpf:"kprobe__filp_close"`
	KprobeSecurityBprmCheck             *ebpf.ProgramSpec `ebpf:"kprobe__security_bprm_check"`
	KprobeSecurityFileOpen              *ebpf.ProgramSpec `ebpf:"kprobe__security_file_open"`
	KprobeSecurityPathChmod             *ebpf.ProgramSpec `ebpf:"kprobe__security_path_chmod"`
	KprobeSecurityPathChown             *ebpf.ProgramSpec `ebpf:"kprobe__security_path_chown"`
	KprobeSecurityPathChroot            *ebpf.ProgramSpec `ebpf:"kprobe__security_path_chroot"`
	KprobeSecurityPathLink              *ebpf.ProgramSpec `ebpf:"kprobe__security_path_link"`
	KprobeSecurityPathMkdir             *ebpf.ProgramSpec `ebpf:"kprobe__security_path_mkdir"`
	KprobeSecurityPathRename            *ebpf.ProgramSpec `ebpf:"kprobe__security_path_rename"`
	KprobeSecurityPathRmdir             *ebpf.ProgramSpec `ebpf:"kprobe__security_path_rmdir"`
	KprobeSecurityPathUnlink            *ebpf.ProgramSpec `ebpf:"kprobe__security_path_unlink"`
	KprobeSecurityPtraceAccessCheck     *ebpf.ProgramSpec `ebpf:"kprobe__security_ptrace_access_check"`
	KprobeSecurityTaskKill              *ebpf.ProgramSpec `ebpf:"kprobe__security_task_kill"`
	KprobeSecurityUnixMaySend           *ebpf.ProgramSpec `ebpf:"kprobe__security_unix_may_send"`
	KprobeSecurityUnixStreamConnect     *ebpf.ProgramSpec `ebpf:"kprobe__security_unix_stream_connect"`
	KretprobeInetCskAcceptMonitor       *ebpf.ProgramSpec `ebpf:"kretprobe__inet_csk_accept_monitor"`
	TracepointSchedSchedProcessExit     *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSyscallsSysEnterAccept    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_accept"`
	TracepointSyscallsSysEnterAccept4   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_accept4"`
	TracepointSyscallsSysEnterBind      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_bind"`
	TracepointSyscallsSysEnterCapset    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_capset"`
	TracepointSyscallsSysEnterChmod     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chmod"`
	TracepointSyscallsSysEnterChown     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chown"`
	TracepointSyscallsSysEnterChroot    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_chroot"`
	TracepointSyscallsSysEnterClone     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterClone3    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_clone3"`
	TracepointSyscallsSysEnterClose     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_close"`
	TracepointSyscallsSysEnterConnect   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterExecve    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterExecveat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execveat"`
	TracepointSyscallsSysEnterExit      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_exit"`
	TracepointSyscallsSysEnterExitGroup *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_exit_group"`
	TracepointSyscallsSysEnterFchmod    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchmod"`
	TracepointSyscallsSysEnterFchmodat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchmodat"`
	TracepointSyscallsSysEnterFchown    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchown"`
	TracepointSyscallsSysEnterFchownat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_fchownat"`
	TracepointSyscallsSysEnterKill      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterLink      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_link"`
	TracepointSyscallsSysEnterLinkat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_linkat"`
	TracepointSyscallsSysEnterListen    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_listen"`
	TracepointSyscallsSysEnterMkdir     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mkdir"`
	TracepointSyscallsSysEnterMkdirat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mkdirat"`
	TracepointSyscallsSysEnterMount     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterOpen      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_open"`
	TracepointSyscallsSysEnterOpenat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterOpenat2   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat2"`
	TracepointSyscallsSysEnterPtrace    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
	TracepointSyscallsSysEnterRename    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_rename"`
	TracepointSyscallsSysEnterRenameat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_renameat"`
	TracepointSyscallsSysEnterRenameat2 *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_renameat2"`
	TracepointSyscallsSysEnterRmdir     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_rmdir"`
	TracepointSyscallsSysEnterSetfsgid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setfsgid"`
	TracepointSyscallsSysEnterSetfsuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setfsuid"`
	TracepointSyscallsSysEnterSetgid    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetns     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setns"`
	TracepointSyscallsSysEnterSetregid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetresgid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setresgid"`
	TracepointSyscallsSysEnterSetresuid *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setresuid"`
	TracepointSyscallsSysEnterSetreuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetrlimit *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setrlimit"`
	TracepointSyscallsSysEnterSetuid    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
	TracepointSyscallsSysEnterSocket    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_socket"`
	TracepointSyscallsSysEnterSymlink   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_symlink"`
	TracepointSyscallsSysEnterSymlinkat *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_symlinkat"`
	TracepointSyscallsSysEnterTgkill    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_tgkill"`
	TracepointSyscallsSysEnterUmount    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_umount"`
	TracepointSyscallsSysEnterUnlink    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unlink"`
	TracepointSyscallsSysEnterUnlinkat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unlinkat"`
	TracepointSyscallsSysEnterUnshare   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_unshare"`
	TracepointSyscallsSysExitAccept     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_accept"`
	TracepointSyscallsSysExitAccept4    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_accept4"`
	TracepointSyscallsSysExitBind       *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_bind"`
	TracepointSyscallsSysExitCapset     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_capset"`
	TracepointSyscallsSysExitChmod      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_chmod"`
	TracepointSyscallsSysExitChown      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_chown"`
	TracepointSyscallsSysExitChroot     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_chroot"`
	TracepointSyscallsSysExitClone      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_clone"`
	TracepointSyscallsSysExitClone3     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_clone3"`
	TracepointSyscallsSysExitClose      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_close"`
	TracepointSyscallsSysExitConnect    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_connect"`
	TracepointSyscallsSysExitExecve     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_execve"`
	TracepointSyscallsSysExitExecveat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_execveat"`
	TracepointSyscallsSysExitExit       *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_exit"`
	TracepointSyscallsSysExitExitGroup  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_exit_group"`
	TracepointSyscallsSysExitFchmod     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_fchmod"`
	TracepointSyscallsSysExitFchmodat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_fchmodat"`
	TracepointSyscallsSysExitFchown     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_fchown"`
	TracepointSyscallsSysExitFchownat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_fchownat"`
	TracepointSyscallsSysExitKill       *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_kill"`
	TracepointSyscallsSysExitLink       *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_link"`
	TracepointSyscallsSysExitLinkat     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_linkat"`
	TracepointSyscallsSysExitListen     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_listen"`
	TracepointSyscallsSysExitMkdir      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_mkdir"`
	TracepointSyscallsSysExitMkdirat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_mkdirat"`
	TracepointSyscallsSysExitMount      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_mount"`
	TracepointSyscallsSysExitOpen       *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_open"`
	TracepointSyscallsSysExitOpenat     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat"`
	TracepointSyscallsSysExitOpenat2    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat2"`
	TracepointSyscallsSysExitPtrace     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_ptrace"`
	TracepointSyscallsSysExitRename     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_rename"`
	TracepointSyscallsSysExitRenameat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_renameat"`
	TracepointSyscallsSysExitRenameat2  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_renameat2"`
	TracepointSyscallsSysExitRmdir      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_rmdir"`
	TracepointSyscallsSysExitSetfsgid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setfsgid"`
	TracepointSyscallsSysExitSetfsuid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setfsuid"`
	TracepointSyscallsSysExitSetgid     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setgid"`
	TracepointSyscallsSysExitSetns      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setns"`
	TracepointSyscallsSysExitSetregid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setregid"`
	TracepointSyscallsSysExitSetresgid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setresgid"`
	TracepointSyscallsSysExitSetresuid  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setresuid"`
	TracepointSyscallsSysExitSetreuid   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setreuid"`
	TracepointSyscallsSysExitSetrlimit  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setrlimit"`
	TracepointSyscallsSysExitSetuid     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_setuid"`
	TracepointSyscallsSysExitSocket     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_socket"`
	TracepointSyscallsSysExitSymlink    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_symlink"`
	TracepointSyscallsSysExitSymlinkat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_symlinkat"`
	TracepointSyscallsSysExitTgkill     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_tgkill"`
	TracepointSyscallsSysExitUmount     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_umount"`
	TracepointSyscallsSysExitUnlink     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_unlink"`
	TracepointSyscallsSysExitUnlinkat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_unlinkat"`
	TracepointSyscallsSysExitUnshare    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_unshare"`
}

// system_eventsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type system_eventsMapSpecs struct {
	StBufMap             *ebpf.MapSpec `ebpf:"st_buf_map"`
	StBufOffsetMap       *ebpf.MapSpec `ebpf:"st_buf_offset_map"`
	StCriticalEventRb    *ebpf.MapSpec `ebpf:"st_critical_event_rb"`
	StNonCriticalEventRb *ebpf.MapSpec `ebpf:"st_non_critical_event_rb"`
	StSeqMap             *ebpf.MapSpec `ebpf:"st_seq_map"`
	StSkipNsMap          *ebpf.MapSpec `ebpf:"st_skip_ns_map"`
	StSrcMap             *ebpf.MapSpec `ebpf:"st_src_map"`
	StTmpBufMap          *ebpf.MapSpec `ebpf:"st_tmp_buf_map"`
}

// system_eventsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type system_eventsVariableSpecs struct {
}

// system_eventsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSystem_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type system_eventsObjects struct {
	system_eventsPrograms
	system_eventsMaps
	system_eventsVariables
}

func (o *system_eventsObjects) Close() error {
	return _System_eventsClose(
		&o.system_eventsPrograms,
		&o.system_eventsMaps,
	)
}

// system_eventsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSystem_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type system_eventsMaps struct {
	StBufMap             *ebpf.Map `ebpf:"st_buf_map"`
	StBufOffsetMap       *ebpf.Map `ebpf:"st_buf_offset_map"`
	StCriticalEventRb    *ebpf.Map `ebpf:"st_critical_event_rb"`
	StNonCriticalEventRb *ebpf.Map `ebpf:"st_non_critical_event_rb"`
	StSeqMap             *ebpf.Map `ebpf:"st_seq_map"`
	StSkipNsMap          *ebpf.Map `ebpf:"st_skip_ns_map"`
	StSrcMap             *ebpf.Map `ebpf:"st_src_map"`
	StTmpBufMap          *ebpf.Map `ebpf:"st_tmp_buf_map"`
}

func (m *system_eventsMaps) Close() error {
	return _System_eventsClose(
		m.StBufMap,
		m.StBufOffsetMap,
		m.StCriticalEventRb,
		m.StNonCriticalEventRb,
		m.StSeqMap,
		m.StSkipNsMap,
		m.StSrcMap,
		m.StTmpBufMap,
	)
}

// system_eventsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSystem_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type system_eventsVariables struct {
}

// system_eventsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSystem_eventsObjects or ebpf.CollectionSpec.LoadAndAssign.
type system_eventsPrograms struct {
	KprobeCapCapable                    *ebpf.Program `ebpf:"kprobe__cap_capable"`
	KprobeFilpClose                     *ebpf.Program `ebpf:"kprobe__filp_close"`
	KprobeSecurityBprmCheck             *ebpf.Program `ebpf:"kprobe__security_bprm_check"`
	KprobeSecurityFileOpen              *ebpf.Program `ebpf:"kprobe__security_file_open"`
	KprobeSecurityPathChmod             *ebpf.Program `ebpf:"kprobe__security_path_chmod"`
	KprobeSecurityPathChown             *ebpf.Program `ebpf:"kprobe__security_path_chown"`
	KprobeSecurityPathChroot            *ebpf.Program `ebpf:"kprobe__security_path_chroot"`
	KprobeSecurityPathLink              *ebpf.Program `ebpf:"kprobe__security_path_link"`
	KprobeSecurityPathMkdir             *ebpf.Program `ebpf:"kprobe__security_path_mkdir"`
	KprobeSecurityPathRename            *ebpf.Program `ebpf:"kprobe__security_path_rename"`
	KprobeSecurityPathRmdir             *ebpf.Program `ebpf:"kprobe__security_path_rmdir"`
	KprobeSecurityPathUnlink            *ebpf.Program `ebpf:"kprobe__security_path_unlink"`
	KprobeSecurityPtraceAccessCheck     *ebpf.Program `ebpf:"kprobe__security_ptrace_access_check"`
	KprobeSecurityTaskKill              *ebpf.Program `ebpf:"kprobe__security_task_kill"`
	KprobeSecurityUnixMaySend           *ebpf.Program `ebpf:"kprobe__security_unix_may_send"`
	KprobeSecurityUnixStreamConnect     *ebpf.Program `ebpf:"kprobe__security_unix_stream_connect"`
	KretprobeInetCskAcceptMonitor       *ebpf.Program `ebpf:"kretprobe__inet_csk_accept_monitor"`
	TracepointSchedSchedProcessExit     *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSyscallsSysEnterAccept    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_accept"`
	TracepointSyscallsSysEnterAccept4   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_accept4"`
	TracepointSyscallsSysEnterBind      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_bind"`
	TracepointSyscallsSysEnterCapset    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_capset"`
	TracepointSyscallsSysEnterChmod     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chmod"`
	TracepointSyscallsSysEnterChown     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chown"`
	TracepointSyscallsSysEnterChroot    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_chroot"`
	TracepointSyscallsSysEnterClone     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_clone"`
	TracepointSyscallsSysEnterClone3    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_clone3"`
	TracepointSyscallsSysEnterClose     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_close"`
	TracepointSyscallsSysEnterConnect   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_connect"`
	TracepointSyscallsSysEnterExecve    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterExecveat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execveat"`
	TracepointSyscallsSysEnterExit      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_exit"`
	TracepointSyscallsSysEnterExitGroup *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_exit_group"`
	TracepointSyscallsSysEnterFchmod    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchmod"`
	TracepointSyscallsSysEnterFchmodat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchmodat"`
	TracepointSyscallsSysEnterFchown    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchown"`
	TracepointSyscallsSysEnterFchownat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_fchownat"`
	TracepointSyscallsSysEnterKill      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_kill"`
	TracepointSyscallsSysEnterLink      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_link"`
	TracepointSyscallsSysEnterLinkat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_linkat"`
	TracepointSyscallsSysEnterListen    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_listen"`
	TracepointSyscallsSysEnterMkdir     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mkdir"`
	TracepointSyscallsSysEnterMkdirat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mkdirat"`
	TracepointSyscallsSysEnterMount     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_mount"`
	TracepointSyscallsSysEnterOpen      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_open"`
	TracepointSyscallsSysEnterOpenat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterOpenat2   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat2"`
	TracepointSyscallsSysEnterPtrace    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_ptrace"`
	TracepointSyscallsSysEnterRename    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_rename"`
	TracepointSyscallsSysEnterRenameat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_renameat"`
	TracepointSyscallsSysEnterRenameat2 *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_renameat2"`
	TracepointSyscallsSysEnterRmdir     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_rmdir"`
	TracepointSyscallsSysEnterSetfsgid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setfsgid"`
	TracepointSyscallsSysEnterSetfsuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setfsuid"`
	TracepointSyscallsSysEnterSetgid    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setgid"`
	TracepointSyscallsSysEnterSetns     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setns"`
	TracepointSyscallsSysEnterSetregid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setregid"`
	TracepointSyscallsSysEnterSetresgid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setresgid"`
	TracepointSyscallsSysEnterSetresuid *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setresuid"`
	TracepointSyscallsSysEnterSetreuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setreuid"`
	TracepointSyscallsSysEnterSetrlimit *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setrlimit"`
	TracepointSyscallsSysEnterSetuid    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_setuid"`
	TracepointSyscallsSysEnterSocket    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_socket"`
	TracepointSyscallsSysEnterSymlink   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_symlink"`
	TracepointSyscallsSysEnterSymlinkat *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_symlinkat"`
	TracepointSyscallsSysEnterTgkill    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_tgkill"`
	TracepointSyscallsSysEnterUmount    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_umount"`
	TracepointSyscallsSysEnterUnlink    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unlink"`
	TracepointSyscallsSysEnterUnlinkat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unlinkat"`
	TracepointSyscallsSysEnterUnshare   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_unshare"`
	TracepointSyscallsSysExitAccept     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_accept"`
	TracepointSyscallsSysExitAccept4    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_accept4"`
	TracepointSyscallsSysExitBind       *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_bind"`
	TracepointSyscallsSysExitCapset     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_capset"`
	TracepointSyscallsSysExitChmod      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_chmod"`
	TracepointSyscallsSysExitChown      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_chown"`
	TracepointSyscallsSysExitChroot     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_chroot"`
	TracepointSyscallsSysExitClone      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_clone"`
	TracepointSyscallsSysExitClone3     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_clone3"`
	TracepointSyscallsSysExitClose      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_close"`
	TracepointSyscallsSysExitConnect    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_connect"`
	TracepointSyscallsSysExitExecve     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_execve"`
	TracepointSyscallsSysExitExecveat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_execveat"`
	TracepointSyscallsSysExitExit       *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_exit"`
	TracepointSyscallsSysExitExitGroup  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_exit_group"`
	TracepointSyscallsSysExitFchmod     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_fchmod"`
	TracepointSyscallsSysExitFchmodat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_fchmodat"`
	TracepointSyscallsSysExitFchown     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_fchown"`
	TracepointSyscallsSysExitFchownat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_fchownat"`
	TracepointSyscallsSysExitKill       *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_kill"`
	TracepointSyscallsSysExitLink       *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_link"`
	TracepointSyscallsSysExitLinkat     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_linkat"`
	TracepointSyscallsSysExitListen     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_listen"`
	TracepointSyscallsSysExitMkdir      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_mkdir"`
	TracepointSyscallsSysExitMkdirat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_mkdirat"`
	TracepointSyscallsSysExitMount      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_mount"`
	TracepointSyscallsSysExitOpen       *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_open"`
	TracepointSyscallsSysExitOpenat     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat"`
	TracepointSyscallsSysExitOpenat2    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat2"`
	TracepointSyscallsSysExitPtrace     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_ptrace"`
	TracepointSyscallsSysExitRename     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_rename"`
	TracepointSyscallsSysExitRenameat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_renameat"`
	TracepointSyscallsSysExitRenameat2  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_renameat2"`
	TracepointSyscallsSysExitRmdir      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_rmdir"`
	TracepointSyscallsSysExitSetfsgid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setfsgid"`
	TracepointSyscallsSysExitSetfsuid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setfsuid"`
	TracepointSyscallsSysExitSetgid     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setgid"`
	TracepointSyscallsSysExitSetns      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setns"`
	TracepointSyscallsSysExitSetregid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setregid"`
	TracepointSyscallsSysExitSetresgid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setresgid"`
	TracepointSyscallsSysExitSetresuid  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setresuid"`
	TracepointSyscallsSysExitSetreuid   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setreuid"`
	TracepointSyscallsSysExitSetrlimit  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setrlimit"`
	TracepointSyscallsSysExitSetuid     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_setuid"`
	TracepointSyscallsSysExitSocket     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_socket"`
	TracepointSyscallsSysExitSymlink    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_symlink"`
	TracepointSyscallsSysExitSymlinkat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_symlinkat"`
	TracepointSyscallsSysExitTgkill     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_tgkill"`
	TracepointSyscallsSysExitUmount     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_umount"`
	TracepointSyscallsSysExitUnlink     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_unlink"`
	TracepointSyscallsSysExitUnlinkat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_unlinkat"`
	TracepointSyscallsSysExitUnshare    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_unshare"`
}

func (p *system_eventsPrograms) Close() error {
	return _System_eventsClose(
		p.KprobeCapCapable,
		p.KprobeFilpClose,
		p.KprobeSecurityBprmCheck,
		p.KprobeSecurityFileOpen,
		p.KprobeSecurityPathChmod,
		p.KprobeSecurityPathChown,
		p.KprobeSecurityPathChroot,
		p.KprobeSecurityPathLink,
		p.KprobeSecurityPathMkdir,
		p.KprobeSecurityPathRename,
		p.KprobeSecurityPathRmdir,
		p.KprobeSecurityPathUnlink,
		p.KprobeSecurityPtraceAccessCheck,
		p.KprobeSecurityTaskKill,
		p.KprobeSecurityUnixMaySend,
		p.KprobeSecurityUnixStreamConnect,
		p.KretprobeInetCskAcceptMonitor,
		p.TracepointSchedSchedProcessExit,
		p.TracepointSyscallsSysEnterAccept,
		p.TracepointSyscallsSysEnterAccept4,
		p.TracepointSyscallsSysEnterBind,
		p.TracepointSyscallsSysEnterCapset,
		p.TracepointSyscallsSysEnterChmod,
		p.TracepointSyscallsSysEnterChown,
		p.TracepointSyscallsSysEnterChroot,
		p.TracepointSyscallsSysEnterClone,
		p.TracepointSyscallsSysEnterClone3,
		p.TracepointSyscallsSysEnterClose,
		p.TracepointSyscallsSysEnterConnect,
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysEnterExecveat,
		p.TracepointSyscallsSysEnterExit,
		p.TracepointSyscallsSysEnterExitGroup,
		p.TracepointSyscallsSysEnterFchmod,
		p.TracepointSyscallsSysEnterFchmodat,
		p.TracepointSyscallsSysEnterFchown,
		p.TracepointSyscallsSysEnterFchownat,
		p.TracepointSyscallsSysEnterKill,
		p.TracepointSyscallsSysEnterLink,
		p.TracepointSyscallsSysEnterLinkat,
		p.TracepointSyscallsSysEnterListen,
		p.TracepointSyscallsSysEnterMkdir,
		p.TracepointSyscallsSysEnterMkdirat,
		p.TracepointSyscallsSysEnterMount,
		p.TracepointSyscallsSysEnterOpen,
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysEnterOpenat2,
		p.TracepointSyscallsSysEnterPtrace,
		p.TracepointSyscallsSysEnterRename,
		p.TracepointSyscallsSysEnterRenameat,
		p.TracepointSyscallsSysEnterRenameat2,
		p.TracepointSyscallsSysEnterRmdir,
		p.TracepointSyscallsSysEnterSetfsgid,
		p.TracepointSyscallsSysEnterSetfsuid,
		p.TracepointSyscallsSysEnterSetgid,
		p.TracepointSyscallsSysEnterSetns,
		p.TracepointSyscallsSysEnterSetregid,
		p.TracepointSyscallsSysEnterSetresgid,
		p.TracepointSyscallsSysEnterSetresuid,
		p.TracepointSyscallsSysEnterSetreuid,
		p.TracepointSyscallsSysEnterSetrlimit,
		p.TracepointSyscallsSysEnterSetuid,
		p.TracepointSyscallsSysEnterSocket,
		p.TracepointSyscallsSysEnterSymlink,
		p.TracepointSyscallsSysEnterSymlinkat,
		p.TracepointSyscallsSysEnterTgkill,
		p.TracepointSyscallsSysEnterUmount,
		p.TracepointSyscallsSysEnterUnlink,
		p.TracepointSyscallsSysEnterUnlinkat,
		p.TracepointSyscallsSysEnterUnshare,
		p.TracepointSyscallsSysExitAccept,
		p.TracepointSyscallsSysExitAccept4,
		p.TracepointSyscallsSysExitBind,
		p.TracepointSyscallsSysExitCapset,
		p.TracepointSyscallsSysExitChmod,
		p.TracepointSyscallsSysExitChown,
		p.TracepointSyscallsSysExitChroot,
		p.TracepointSyscallsSysExitClone,
		p.TracepointSyscallsSysExitClone3,
		p.TracepointSyscallsSysExitClose,
		p.TracepointSyscallsSysExitConnect,
		p.TracepointSyscallsSysExitExecve,
		p.TracepointSyscallsSysExitExecveat,
		p.TracepointSyscallsSysExitExit,
		p.TracepointSyscallsSysExitExitGroup,
		p.TracepointSyscallsSysExitFchmod,
		p.TracepointSyscallsSysExitFchmodat,
		p.TracepointSyscallsSysExitFchown,
		p.TracepointSyscallsSysExitFchownat,
		p.TracepointSyscallsSysExitKill,
		p.TracepointSyscallsSysExitLink,
		p.TracepointSyscallsSysExitLinkat,
		p.TracepointSyscallsSysExitListen,
		p.TracepointSyscallsSysExitMkdir,
		p.TracepointSyscallsSysExitMkdirat,
		p.TracepointSyscallsSysExitMount,
		p.TracepointSyscallsSysExitOpen,
		p.TracepointSyscallsSysExitOpenat,
		p.TracepointSyscallsSysExitOpenat2,
		p.TracepointSyscallsSysExitPtrace,
		p.TracepointSyscallsSysExitRename,
		p.TracepointSyscallsSysExitRenameat,
		p.TracepointSyscallsSysExitRenameat2,
		p.TracepointSyscallsSysExitRmdir,
		p.TracepointSyscallsSysExitSetfsgid,
		p.TracepointSyscallsSysExitSetfsuid,
		p.TracepointSyscallsSysExitSetgid,
		p.TracepointSyscallsSysExitSetns,
		p.TracepointSyscallsSysExitSetregid,
		p.TracepointSyscallsSysExitSetresgid,
		p.TracepointSyscallsSysExitSetresuid,
		p.TracepointSyscallsSysExitSetreuid,
		p.TracepointSyscallsSysExitSetrlimit,
		p.TracepointSyscallsSysExitSetuid,
		p.TracepointSyscallsSysExitSocket,
		p.TracepointSyscallsSysExitSymlink,
		p.TracepointSyscallsSysExitSymlinkat,
		p.TracepointSyscallsSysExitTgkill,
		p.TracepointSyscallsSysExitUmount,
		p.TracepointSyscallsSysExitUnlink,
		p.TracepointSyscallsSysExitUnlinkat,
		p.TracepointSyscallsSysExitUnshare,
	)
}

func _System_eventsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed system_events_x86_bpfel.o
var _System_eventsBytes []byte
