// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package enforcer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_enforcerBpfeCapKey struct {
	_        structs.HostLayout
	PodInode uint64
	SrcInode uint64
	CapId    uint32
	Pad      uint32
}

type bpf_enforcerBpfeFileKey struct {
	_          structs.HostLayout
	PodInode   uint64
	SrcInode   uint64
	TgtInode   uint64
	Permission uint8
	Pad        [7]uint8
}

type bpf_enforcerBpfePostureKey struct {
	_        structs.HostLayout
	PodInode uint64
	SrcInode uint64
	Domain   uint32
	Pad      uint32
}

type bpf_enforcerBpfePostureVal struct {
	_        structs.HostLayout
	Action   uint8
	Pad      [3]uint8
	PolicyId uint32
}

type bpf_enforcerBpfeProcKey struct {
	_        structs.HostLayout
	PodInode uint64
	SrcInode uint64
	TgtInode uint64
}

type bpf_enforcerBpfePtraceKey struct {
	_           structs.HostLayout
	PodInode    uint64
	SrcInode    uint64
	TargetInode uint64
}

type bpf_enforcerBpfePtraceVal struct {
	_             structs.HostLayout
	ActionTrace   uint8
	ActionRead    uint8
	ActionTraceby uint8
	ActionReadby  uint8
	PolicyId      uint32
}

type bpf_enforcerBpfeRuleVal struct {
	_        structs.HostLayout
	Action   uint8
	Pad      [3]uint8
	PolicyId uint32
}

type bpf_enforcerBpfeSignalKey struct {
	_           structs.HostLayout
	PodInode    uint64
	SrcInode    uint64
	TargetInode uint64
	Pad         uint32
	_           [4]byte
}

type bpf_enforcerBpfeSignalVal struct {
	_         structs.HostLayout
	BlockMask uint32
	AuditMask uint32
	PolicyId  uint32
	Pad       uint32
}

type bpf_enforcerBpfeUnixKey struct {
	_          structs.HostLayout
	PodInode   uint64
	SrcInode   uint64
	PathHash   uint32
	SockType   uint8
	Permission uint8
	Pad        [2]uint8
}

type bpf_enforcerBpfeUnixSkCtx struct {
	_        structs.HostLayout
	Cgid     uint64
	PathHash uint32
	SockType uint8
	Pad      [3]uint8
}

// loadBpf_enforcer returns the embedded CollectionSpec for bpf_enforcer.
func loadBpf_enforcer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_enforcerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_enforcer: %w", err)
	}

	return spec, err
}

// loadBpf_enforcerObjects loads bpf_enforcer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_enforcerObjects
//	*bpf_enforcerPrograms
//	*bpf_enforcerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_enforcerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_enforcer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_enforcerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_enforcerSpecs struct {
	bpf_enforcerProgramSpecs
	bpf_enforcerMapSpecs
	bpf_enforcerVariableSpecs
}

// bpf_enforcerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_enforcerProgramSpecs struct {
	BpfeBprmCheck         *ebpf.ProgramSpec `ebpf:"bpfe_bprm_check"`
	BpfeCapable           *ebpf.ProgramSpec `ebpf:"bpfe_capable"`
	BpfeFileOpen          *ebpf.ProgramSpec `ebpf:"bpfe_file_open"`
	BpfeFilePermission    *ebpf.ProgramSpec `ebpf:"bpfe_file_permission"`
	BpfeMmapFile          *ebpf.ProgramSpec `ebpf:"bpfe_mmap_file"`
	BpfePathChmod         *ebpf.ProgramSpec `ebpf:"bpfe_path_chmod"`
	BpfePathChown         *ebpf.ProgramSpec `ebpf:"bpfe_path_chown"`
	BpfePathLink          *ebpf.ProgramSpec `ebpf:"bpfe_path_link"`
	BpfePathMkdir         *ebpf.ProgramSpec `ebpf:"bpfe_path_mkdir"`
	BpfePathMknod         *ebpf.ProgramSpec `ebpf:"bpfe_path_mknod"`
	BpfePathRename        *ebpf.ProgramSpec `ebpf:"bpfe_path_rename"`
	BpfePathRmdir         *ebpf.ProgramSpec `ebpf:"bpfe_path_rmdir"`
	BpfePathSymlink       *ebpf.ProgramSpec `ebpf:"bpfe_path_symlink"`
	BpfePathTruncate      *ebpf.ProgramSpec `ebpf:"bpfe_path_truncate"`
	BpfePathUnlink        *ebpf.ProgramSpec `ebpf:"bpfe_path_unlink"`
	BpfePtraceAccess      *ebpf.ProgramSpec `ebpf:"bpfe_ptrace_access"`
	BpfePtraceTraceme     *ebpf.ProgramSpec `ebpf:"bpfe_ptrace_traceme"`
	BpfeSkFree            *ebpf.ProgramSpec `ebpf:"bpfe_sk_free"`
	BpfeSocketBind        *ebpf.ProgramSpec `ebpf:"bpfe_socket_bind"`
	BpfeSocketListen      *ebpf.ProgramSpec `ebpf:"bpfe_socket_listen"`
	BpfeSocketPostCreate  *ebpf.ProgramSpec `ebpf:"bpfe_socket_post_create"`
	BpfeTaskKill          *ebpf.ProgramSpec `ebpf:"bpfe_task_kill"`
	BpfeUnixMaySend       *ebpf.ProgramSpec `ebpf:"bpfe_unix_may_send"`
	BpfeUnixStreamConnect *ebpf.ProgramSpec `ebpf:"bpfe_unix_stream_connect"`
}

// bpf_enforcerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_enforcerMapSpecs struct {
	BpfeAlertsRb       *ebpf.MapSpec `ebpf:"bpfe_alerts_rb"`
	BpfeCapRules       *ebpf.MapSpec `ebpf:"bpfe_cap_rules"`
	BpfeFileRules      *ebpf.MapSpec `ebpf:"bpfe_file_rules"`
	BpfeManagedCgroups *ebpf.MapSpec `ebpf:"bpfe_managed_cgroups"`
	BpfePosture        *ebpf.MapSpec `ebpf:"bpfe_posture"`
	BpfeProcRules      *ebpf.MapSpec `ebpf:"bpfe_proc_rules"`
	BpfePtraceRules    *ebpf.MapSpec `ebpf:"bpfe_ptrace_rules"`
	BpfeSignalRules    *ebpf.MapSpec `ebpf:"bpfe_signal_rules"`
	BpfeUnixRules      *ebpf.MapSpec `ebpf:"bpfe_unix_rules"`
	BpfeUnixSkMap      *ebpf.MapSpec `ebpf:"bpfe_unix_sk_map"`
}

// bpf_enforcerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_enforcerVariableSpecs struct {
}

// bpf_enforcerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_enforcerObjects struct {
	bpf_enforcerPrograms
	bpf_enforcerMaps
	bpf_enforcerVariables
}

func (o *bpf_enforcerObjects) Close() error {
	return _Bpf_enforcerClose(
		&o.bpf_enforcerPrograms,
		&o.bpf_enforcerMaps,
	)
}

// bpf_enforcerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_enforcerMaps struct {
	BpfeAlertsRb       *ebpf.Map `ebpf:"bpfe_alerts_rb"`
	BpfeCapRules       *ebpf.Map `ebpf:"bpfe_cap_rules"`
	BpfeFileRules      *ebpf.Map `ebpf:"bpfe_file_rules"`
	BpfeManagedCgroups *ebpf.Map `ebpf:"bpfe_managed_cgroups"`
	BpfePosture        *ebpf.Map `ebpf:"bpfe_posture"`
	BpfeProcRules      *ebpf.Map `ebpf:"bpfe_proc_rules"`
	BpfePtraceRules    *ebpf.Map `ebpf:"bpfe_ptrace_rules"`
	BpfeSignalRules    *ebpf.Map `ebpf:"bpfe_signal_rules"`
	BpfeUnixRules      *ebpf.Map `ebpf:"bpfe_unix_rules"`
	BpfeUnixSkMap      *ebpf.Map `ebpf:"bpfe_unix_sk_map"`
}

func (m *bpf_enforcerMaps) Close() error {
	return _Bpf_enforcerClose(
		m.BpfeAlertsRb,
		m.BpfeCapRules,
		m.BpfeFileRules,
		m.BpfeManagedCgroups,
		m.BpfePosture,
		m.BpfeProcRules,
		m.BpfePtraceRules,
		m.BpfeSignalRules,
		m.BpfeUnixRules,
		m.BpfeUnixSkMap,
	)
}

// bpf_enforcerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_enforcerVariables struct {
}

// bpf_enforcerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_enforcerPrograms struct {
	BpfeBprmCheck         *ebpf.Program `ebpf:"bpfe_bprm_check"`
	BpfeCapable           *ebpf.Program `ebpf:"bpfe_capable"`
	BpfeFileOpen          *ebpf.Program `ebpf:"bpfe_file_open"`
	BpfeFilePermission    *ebpf.Program `ebpf:"bpfe_file_permission"`
	BpfeMmapFile          *ebpf.Program `ebpf:"bpfe_mmap_file"`
	BpfePathChmod         *ebpf.Program `ebpf:"bpfe_path_chmod"`
	BpfePathChown         *ebpf.Program `ebpf:"bpfe_path_chown"`
	BpfePathLink          *ebpf.Program `ebpf:"bpfe_path_link"`
	BpfePathMkdir         *ebpf.Program `ebpf:"bpfe_path_mkdir"`
	BpfePathMknod         *ebpf.Program `ebpf:"bpfe_path_mknod"`
	BpfePathRename        *ebpf.Program `ebpf:"bpfe_path_rename"`
	BpfePathRmdir         *ebpf.Program `ebpf:"bpfe_path_rmdir"`
	BpfePathSymlink       *ebpf.Program `ebpf:"bpfe_path_symlink"`
	BpfePathTruncate      *ebpf.Program `ebpf:"bpfe_path_truncate"`
	BpfePathUnlink        *ebpf.Program `ebpf:"bpfe_path_unlink"`
	BpfePtraceAccess      *ebpf.Program `ebpf:"bpfe_ptrace_access"`
	BpfePtraceTraceme     *ebpf.Program `ebpf:"bpfe_ptrace_traceme"`
	BpfeSkFree            *ebpf.Program `ebpf:"bpfe_sk_free"`
	BpfeSocketBind        *ebpf.Program `ebpf:"bpfe_socket_bind"`
	BpfeSocketListen      *ebpf.Program `ebpf:"bpfe_socket_listen"`
	BpfeSocketPostCreate  *ebpf.Program `ebpf:"bpfe_socket_post_create"`
	BpfeTaskKill          *ebpf.Program `ebpf:"bpfe_task_kill"`
	BpfeUnixMaySend       *ebpf.Program `ebpf:"bpfe_unix_may_send"`
	BpfeUnixStreamConnect *ebpf.Program `ebpf:"bpfe_unix_stream_connect"`
}

func (p *bpf_enforcerPrograms) Close() error {
	return _Bpf_enforcerClose(
		p.BpfeBprmCheck,
		p.BpfeCapable,
		p.BpfeFileOpen,
		p.BpfeFilePermission,
		p.BpfeMmapFile,
		p.BpfePathChmod,
		p.BpfePathChown,
		p.BpfePathLink,
		p.BpfePathMkdir,
		p.BpfePathMknod,
		p.BpfePathRename,
		p.BpfePathRmdir,
		p.BpfePathSymlink,
		p.BpfePathTruncate,
		p.BpfePathUnlink,
		p.BpfePtraceAccess,
		p.BpfePtraceTraceme,
		p.BpfeSkFree,
		p.BpfeSocketBind,
		p.BpfeSocketListen,
		p.BpfeSocketPostCreate,
		p.BpfeTaskKill,
		p.BpfeUnixMaySend,
		p.BpfeUnixStreamConnect,
	)
}

func _Bpf_enforcerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_enforcer_x86_bpfel.o
var _Bpf_enforcerBytes []byte
