// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package enforcer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type net_enforcerDefaultPostureKey struct {
	_     structs.HostLayout
	Inode uint64
	Addr  uint64
}

type net_enforcerDnsPendingKey struct {
	_           structs.HostLayout
	QuerierIp   uint32
	DnsServerIp uint32
	QuerierPort uint16
	Txid        uint16
}

type net_enforcerDnsPendingVal struct {
	_        structs.HostLayout
	Ts       uint64
	PidNsId  uint32
	MntNsId  uint32
	Reversed [64]int8
}

type net_enforcerDnsRawBuf struct {
	_    structs.HostLayout
	Data [512]uint8
}

type net_enforcerFqdnIpKey struct {
	_     structs.HostLayout
	Inode uint64
	Addr  uint32
	Pad   uint32
}

type net_enforcerFqdnRuleKey struct {
	_        structs.HostLayout
	Reversed [64]int8
}

type net_enforcerFqdnRuleVal struct {
	_         structs.HostLayout
	Inode     uint64
	Action    int8
	Direction uint8
	Pad       uint16
	PolicyId  uint32
}

type net_enforcerFqdnTmpBuf struct {
	_   structs.HostLayout
	Buf [256]int8
}

type net_enforcerInodeKey struct {
	_        structs.HostLayout
	CgroupId uint64
	Protocol uint32
	Port     uint32
}

type net_enforcerLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Laddr     uint32
	Inode     uint64
	Proto     uint16
	Port      uint16
	Raddr     uint32
}

type net_enforcerPolicyKey struct {
	_     structs.HostLayout
	Inode uint64
	Saddr uint32
	Daddr uint32
	Proto uint32
	Port  uint32
}

type net_enforcerPolicyVal struct {
	_        structs.HostLayout
	Inode    uint64
	Port     uint16
	Proto    uint8
	Action   int8
	PolicyId uint32
}

type net_enforcerRetVal struct {
	_        structs.HostLayout
	Action   int32
	PolicyId uint32
}

type net_enforcerSessionKey struct {
	_     structs.HostLayout
	Proto uint32
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

// loadNet_enforcer returns the embedded CollectionSpec for net_enforcer.
func loadNet_enforcer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Net_enforcerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load net_enforcer: %w", err)
	}

	return spec, err
}

// loadNet_enforcerObjects loads net_enforcer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*net_enforcerObjects
//	*net_enforcerPrograms
//	*net_enforcerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNet_enforcerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNet_enforcer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// net_enforcerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_enforcerSpecs struct {
	net_enforcerProgramSpecs
	net_enforcerMapSpecs
	net_enforcerVariableSpecs
}

// net_enforcerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_enforcerProgramSpecs struct {
	CgroupSkbEgress            *ebpf.ProgramSpec `ebpf:"cgroup_skb__egress"`
	CgroupSkbEgressDns         *ebpf.ProgramSpec `ebpf:"cgroup_skb__egress_dns"`
	CgroupSkbIngress           *ebpf.ProgramSpec `ebpf:"cgroup_skb__ingress"`
	CgroupSkbIngressDns        *ebpf.ProgramSpec `ebpf:"cgroup_skb__ingress_dns"`
	KprobeInetAutobind         *ebpf.ProgramSpec `ebpf:"kprobe__inet_autobind"`
	KprobeInetBind             *ebpf.ProgramSpec `ebpf:"kprobe__inet_bind"`
	KprobeInetHashConnect      *ebpf.ProgramSpec `ebpf:"kprobe__inet_hash_connect"`
	KprobeInetStreamConnect    *ebpf.ProgramSpec `ebpf:"kprobe__inet_stream_connect"`
	KprobeUdpDestroySock       *ebpf.ProgramSpec `ebpf:"kprobe__udp_destroy_sock"`
	KprobeUdpRecvmsg           *ebpf.ProgramSpec `ebpf:"kprobe__udp_recvmsg"`
	KprobeUdpSendmsg           *ebpf.ProgramSpec `ebpf:"kprobe__udp_sendmsg"`
	KretprobeInetAutobind      *ebpf.ProgramSpec `ebpf:"kretprobe__inet_autobind"`
	KretprobeInetBind          *ebpf.ProgramSpec `ebpf:"kretprobe__inet_bind"`
	KretprobeInetCskAccept     *ebpf.ProgramSpec `ebpf:"kretprobe__inet_csk_accept"`
	KretprobeInetHashConnect   *ebpf.ProgramSpec `ebpf:"kretprobe__inet_hash_connect"`
	KretprobeInetStreamConnect *ebpf.ProgramSpec `ebpf:"kretprobe__inet_stream_connect"`
	KretprobeUdpRecvmsg        *ebpf.ProgramSpec `ebpf:"kretprobe__udp_recvmsg"`
	KretprobeUdpSendmsg        *ebpf.ProgramSpec `ebpf:"kretprobe__udp_sendmsg"`
	TpInetSockSetState         *ebpf.ProgramSpec `ebpf:"tp_inet_sock_set_state"`
}

// net_enforcerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_enforcerMapSpecs struct {
	NeAutobindMap              *ebpf.MapSpec `ebpf:"ne_autobind_map"`
	NeBindSocketMap            *ebpf.MapSpec `ebpf:"ne_bind_socket_map"`
	NeConnectSockMap           *ebpf.MapSpec `ebpf:"ne_connect_sock_map"`
	NeDnsPendingMap            *ebpf.MapSpec `ebpf:"ne_dns_pending_map"`
	NeDnsRawMap                *ebpf.MapSpec `ebpf:"ne_dns_raw_map"`
	NeEgressDefaultPostureMap  *ebpf.MapSpec `ebpf:"ne_egress_default_posture_map"`
	NeEgressLpmMap             *ebpf.MapSpec `ebpf:"ne_egress_lpm_map"`
	NeEgressPolicyMap          *ebpf.MapSpec `ebpf:"ne_egress_policy_map"`
	NeEventRb                  *ebpf.MapSpec `ebpf:"ne_event_rb"`
	NeFqdnEgressMap            *ebpf.MapSpec `ebpf:"ne_fqdn_egress_map"`
	NeFqdnIngressMap           *ebpf.MapSpec `ebpf:"ne_fqdn_ingress_map"`
	NeFqdnKeyScratchMap        *ebpf.MapSpec `ebpf:"ne_fqdn_key_scratch_map"`
	NeFqdnNotifyRb             *ebpf.MapSpec `ebpf:"ne_fqdn_notify_rb"`
	NeFqdnRulesMap             *ebpf.MapSpec `ebpf:"ne_fqdn_rules_map"`
	NeFqdnTmpMap               *ebpf.MapSpec `ebpf:"ne_fqdn_tmp_map"`
	NeIngressDefaultPostureMap *ebpf.MapSpec `ebpf:"ne_ingress_default_posture_map"`
	NeIngressLpmMap            *ebpf.MapSpec `ebpf:"ne_ingress_lpm_map"`
	NeIngressPolicyMap         *ebpf.MapSpec `ebpf:"ne_ingress_policy_map"`
	NeInodeMap                 *ebpf.MapSpec `ebpf:"ne_inode_map"`
	NeMsgMap                   *ebpf.MapSpec `ebpf:"ne_msg_map"`
	NeSkCache                  *ebpf.MapSpec `ebpf:"ne_sk_cache"`
	NeSkipNsMap                *ebpf.MapSpec `ebpf:"ne_skip_ns_map"`
}

// net_enforcerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type net_enforcerVariableSpecs struct {
}

// net_enforcerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNet_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_enforcerObjects struct {
	net_enforcerPrograms
	net_enforcerMaps
	net_enforcerVariables
}

func (o *net_enforcerObjects) Close() error {
	return _Net_enforcerClose(
		&o.net_enforcerPrograms,
		&o.net_enforcerMaps,
	)
}

// net_enforcerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNet_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_enforcerMaps struct {
	NeAutobindMap              *ebpf.Map `ebpf:"ne_autobind_map"`
	NeBindSocketMap            *ebpf.Map `ebpf:"ne_bind_socket_map"`
	NeConnectSockMap           *ebpf.Map `ebpf:"ne_connect_sock_map"`
	NeDnsPendingMap            *ebpf.Map `ebpf:"ne_dns_pending_map"`
	NeDnsRawMap                *ebpf.Map `ebpf:"ne_dns_raw_map"`
	NeEgressDefaultPostureMap  *ebpf.Map `ebpf:"ne_egress_default_posture_map"`
	NeEgressLpmMap             *ebpf.Map `ebpf:"ne_egress_lpm_map"`
	NeEgressPolicyMap          *ebpf.Map `ebpf:"ne_egress_policy_map"`
	NeEventRb                  *ebpf.Map `ebpf:"ne_event_rb"`
	NeFqdnEgressMap            *ebpf.Map `ebpf:"ne_fqdn_egress_map"`
	NeFqdnIngressMap           *ebpf.Map `ebpf:"ne_fqdn_ingress_map"`
	NeFqdnKeyScratchMap        *ebpf.Map `ebpf:"ne_fqdn_key_scratch_map"`
	NeFqdnNotifyRb             *ebpf.Map `ebpf:"ne_fqdn_notify_rb"`
	NeFqdnRulesMap             *ebpf.Map `ebpf:"ne_fqdn_rules_map"`
	NeFqdnTmpMap               *ebpf.Map `ebpf:"ne_fqdn_tmp_map"`
	NeIngressDefaultPostureMap *ebpf.Map `ebpf:"ne_ingress_default_posture_map"`
	NeIngressLpmMap            *ebpf.Map `ebpf:"ne_ingress_lpm_map"`
	NeIngressPolicyMap         *ebpf.Map `ebpf:"ne_ingress_policy_map"`
	NeInodeMap                 *ebpf.Map `ebpf:"ne_inode_map"`
	NeMsgMap                   *ebpf.Map `ebpf:"ne_msg_map"`
	NeSkCache                  *ebpf.Map `ebpf:"ne_sk_cache"`
	NeSkipNsMap                *ebpf.Map `ebpf:"ne_skip_ns_map"`
}

func (m *net_enforcerMaps) Close() error {
	return _Net_enforcerClose(
		m.NeAutobindMap,
		m.NeBindSocketMap,
		m.NeConnectSockMap,
		m.NeDnsPendingMap,
		m.NeDnsRawMap,
		m.NeEgressDefaultPostureMap,
		m.NeEgressLpmMap,
		m.NeEgressPolicyMap,
		m.NeEventRb,
		m.NeFqdnEgressMap,
		m.NeFqdnIngressMap,
		m.NeFqdnKeyScratchMap,
		m.NeFqdnNotifyRb,
		m.NeFqdnRulesMap,
		m.NeFqdnTmpMap,
		m.NeIngressDefaultPostureMap,
		m.NeIngressLpmMap,
		m.NeIngressPolicyMap,
		m.NeInodeMap,
		m.NeMsgMap,
		m.NeSkCache,
		m.NeSkipNsMap,
	)
}

// net_enforcerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNet_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_enforcerVariables struct {
}

// net_enforcerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNet_enforcerObjects or ebpf.CollectionSpec.LoadAndAssign.
type net_enforcerPrograms struct {
	CgroupSkbEgress            *ebpf.Program `ebpf:"cgroup_skb__egress"`
	CgroupSkbEgressDns         *ebpf.Program `ebpf:"cgroup_skb__egress_dns"`
	CgroupSkbIngress           *ebpf.Program `ebpf:"cgroup_skb__ingress"`
	CgroupSkbIngressDns        *ebpf.Program `ebpf:"cgroup_skb__ingress_dns"`
	KprobeInetAutobind         *ebpf.Program `ebpf:"kprobe__inet_autobind"`
	KprobeInetBind             *ebpf.Program `ebpf:"kprobe__inet_bind"`
	KprobeInetHashConnect      *ebpf.Program `ebpf:"kprobe__inet_hash_connect"`
	KprobeInetStreamConnect    *ebpf.Program `ebpf:"kprobe__inet_stream_connect"`
	KprobeUdpDestroySock       *ebpf.Program `ebpf:"kprobe__udp_destroy_sock"`
	KprobeUdpRecvmsg           *ebpf.Program `ebpf:"kprobe__udp_recvmsg"`
	KprobeUdpSendmsg           *ebpf.Program `ebpf:"kprobe__udp_sendmsg"`
	KretprobeInetAutobind      *ebpf.Program `ebpf:"kretprobe__inet_autobind"`
	KretprobeInetBind          *ebpf.Program `ebpf:"kretprobe__inet_bind"`
	KretprobeInetCskAccept     *ebpf.Program `ebpf:"kretprobe__inet_csk_accept"`
	KretprobeInetHashConnect   *ebpf.Program `ebpf:"kretprobe__inet_hash_connect"`
	KretprobeInetStreamConnect *ebpf.Program `ebpf:"kretprobe__inet_stream_connect"`
	KretprobeUdpRecvmsg        *ebpf.Program `ebpf:"kretprobe__udp_recvmsg"`
	KretprobeUdpSendmsg        *ebpf.Program `ebpf:"kretprobe__udp_sendmsg"`
	TpInetSockSetState         *ebpf.Program `ebpf:"tp_inet_sock_set_state"`
}

func (p *net_enforcerPrograms) Close() error {
	return _Net_enforcerClose(
		p.CgroupSkbEgress,
		p.CgroupSkbEgressDns,
		p.CgroupSkbIngress,
		p.CgroupSkbIngressDns,
		p.KprobeInetAutobind,
		p.KprobeInetBind,
		p.KprobeInetHashConnect,
		p.KprobeInetStreamConnect,
		p.KprobeUdpDestroySock,
		p.KprobeUdpRecvmsg,
		p.KprobeUdpSendmsg,
		p.KretprobeInetAutobind,
		p.KretprobeInetBind,
		p.KretprobeInetCskAccept,
		p.KretprobeInetHashConnect,
		p.KretprobeInetStreamConnect,
		p.KretprobeUdpRecvmsg,
		p.KretprobeUdpSendmsg,
		p.TpInetSockSetState,
	)
}

func _Net_enforcerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed net_enforcer_x86_bpfel.o
var _Net_enforcerBytes []byte
